<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cities')->insert([
            ['name' => 'Tallinn', 'country_id' => 1],
            ['name' => 'Tartu', 'country_id' => 1],
            ['name' => 'Narva', 'country_id' => 1],
            ['name' => 'Pärnu', 'country_id' => 1],
            ['name' => 'Kohtla-Järve', 'country_id' => 1],
            ['name' => 'Viljandi', 'country_id' => 1],
            ['name' => 'Rakvere', 'country_id' => 1],
            ['name' => 'Sillamäe', 'country_id' => 1],
            ['name' => 'Maardu', 'country_id' => 1],
            ['name' => 'Kuressaare', 'country_id' => 1],
            ['name' => 'Võru', 'country_id' => 1],
            ['name' => 'Valga', 'country_id' => 1],
            ['name' => 'Jõhvi', 'country_id' => 1],
            ['name' => 'Paide', 'country_id' => 1],
            ['name' => 'Haapsalu', 'country_id' => 1],
            ['name' => 'Keila', 'country_id' => 1],
            ['name' => 'Saue', 'country_id' => 1],
            ['name' => 'Türi', 'country_id' => 1],
            ['name' => 'Lääne-Nigula', 'country_id' => 1],
            ['name' => 'Rapla', 'country_id' => 1],
            ['name' => 'Ockelbo', 'country_id' => 1],
            ['name' => 'Tamsalu', 'country_id' => 1],
            ['name' => 'Põlva', 'country_id' => 1],
            ['name' => 'Sindi', 'country_id' => 1],
            ['name' => 'Elva', 'country_id' => 1],
            ['name' => 'Jõgeva', 'country_id' => 1],
            ['name' => 'Viljandi', 'country_id' => 1],
            ['name' => 'Kunda', 'country_id' => 1],
            ['name' => 'Väike-Maarja', 'country_id' => 1],
            ['name' => 'Kärdla', 'country_id' => 1],
            ['name' => 'Tõrva', 'country_id' => 1],
            ['name' => 'Harku', 'country_id' => 1],
            ['name' => 'Tamsalu', 'country_id' => 1],
            ['name' => 'Riga', 'country_id' => 2],
            ['name' => 'Daugavpils', 'country_id' => 2],
            ['name' => 'Liepāja', 'country_id' => 2],
            ['name' => 'Jūrmala', 'country_id' => 2],
            ['name' => 'Rēzekne', 'country_id' => 2],
            ['name' => 'Ventspils', 'country_id' => 2],
            ['name' => 'Riga', 'country_id' => 2],
            ['name' => 'Ogre', 'country_id' => 2],
            ['name' => 'Jelgava', 'country_id' => 2],
            ['name' => 'Salaspils', 'country_id' => 2],
            ['name' => 'Kuldīga', 'country_id' => 2],
            ['name' => 'Tukums', 'country_id' => 2],
            ['name' => 'Cēsis', 'country_id' => 2],
            ['name' => 'Bauska', 'country_id' => 2],
            ['name' => 'Valmiera', 'country_id' => 2],
            ['name' => 'Saldus', 'country_id' => 2],
            ['name' => 'Rundāle', 'country_id' => 2],
            ['name' => 'Lielvārde', 'country_id' => 2],
            ['name' => 'Gulbene', 'country_id' => 2],
            ['name' => 'Madona', 'country_id' => 2],
            ['name' => 'Sigulda', 'country_id' => 2],
            ['name' => 'Rūjiena', 'country_id' => 2],
            ['name' => 'Kārsava', 'country_id' => 2],
            ['name' => 'Krāslava', 'country_id' => 2],
            ['name' => 'Alūksne', 'country_id' => 2],
            ['name' => 'Talsi', 'country_id' => 2],
            ['name' => 'Brocēni', 'country_id' => 2],
            ['name' => 'Iecava', 'country_id' => 2],
            ['name' => 'Sabile', 'country_id' => 2],
            ['name' => 'Vilnius', 'country_id' => 3],
            ['name' => 'Kaunas', 'country_id' => 3],
            ['name' => 'Klaipėda', 'country_id' => 3],
            ['name' => 'Šiauliai', 'country_id' => 3],
            ['name' => 'Panevėžys', 'country_id' => 3],
            ['name' => 'Alytus', 'country_id' => 3],
            ['name' => 'Marijampolė', 'country_id' => 3],
            ['name' => 'Mažeikiai', 'country_id' => 3],
            ['name' => 'Jonava', 'country_id' => 3],
            ['name' => 'Ukmergė', 'country_id' => 3],
            ['name' => 'Utena', 'country_id' => 3],
            ['name' => 'Kėdainiai', 'country_id' => 3],
            ['name' => 'Klaipėda', 'country_id' => 3],
            ['name' => 'Visaginas', 'country_id' => 3],
            ['name' => 'Druskininkai', 'country_id' => 3],
            ['name' => 'Palanga', 'country_id' => 3],
            ['name' => 'Silale', 'country_id' => 3],
            ['name' => 'Neringa', 'country_id' => 3],
            ['name' => 'Tauragė', 'country_id' => 3],
            ['name' => 'Radviliškis', 'country_id' => 3],
            ['name' => 'Šakiai', 'country_id' => 3],
            ['name' => 'Kupiškis', 'country_id' => 3],
            ['name' => 'Raseiniai', 'country_id' => 3],
            ['name' => 'Anykščiai', 'country_id' => 3],
            ['name' => 'Šilalė', 'country_id' => 3],
            ['name' => 'Plungė', 'country_id' => 3],
            ['name' => 'Kelmė', 'country_id' => 3],
        ]);
    }
}
